name: Greetings

on: 
  pull_request_target:
    types: [opened]
  issues:
    types: [opened]

permissions:
  issues: write
  pull-requests: write

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Thanks for creating the issue,Please read the Pinned issued first and Readme.md in each Pull Request you made. Keep learning...'
        pr-message: 'keep doing it'
